version: '3.8'

services:
  db:
    image: postgres:12.3-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      args:
        WORKDIR: $WORKDIR
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      ADMIN_DOMAIN: "localhost:$ADMIN_PORT"
      SERVICE_DOMAIN: "localhost:$SERVICE_PORT"
    volumes:
      - ./api:/$WORKDIR
    depends_on:
      - db
    ports:
      - "$API_PORT:$CONTAINER_PORT"
    command: sh -c 'rm -f tmp/pids/server.pid && bundle && rails s -b 0.0.0.0'

  admin:
    build:
      context: ./admin
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
        API_URL: "http://localhost:$API_PORT/admin"
    command: sh -c 'yarn && yarn run dev'
    volumes:
      - ./admin:/$WORKDIR
    ports:
      - "$ADMIN_PORT:$CONTAINER_PORT"
    depends_on:
      - api

  service:
    build:
      context: ./service
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
        API_URL: "http://localhost:$API_PORT/service"
    command: sh -c 'yarn && yarn run dev'
    volumes:
      - ./service:/$WORKDIR
    ports:
      - "$SERVICE_PORT:$CONTAINER_PORT"
    depends_on:
      - api
