aws:
  s3:
    presigned_url:
      expires_in: <%= 1.minutes.to_i %>

models:
  competition:
    rid_length: 24

controllers:
  image_upload:
    max_file_size: 1_048_576 # 1.megabytes
    max_file_name_size: 200
    allowed_file_types:
      - image/jpg
      - image/jpeg
      - image/png
      - image/gif

wedding:
  title: '2021年7月10日 小松秀生・未菜里 結婚式 クイズ大会'
  id: shuseiminariwedding21710